version: '2'

services:
    db:
        build: docker/postgres
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        user: "${UID}:${GID}"
        ports:
            - "5433:5432"
        expose:
            - 5433
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    php:
        user: "${UID}:${GID}"
        build: docker/php7fpm
        depends_on:
            - db
        expose:
            - 9000
        working_dir: /app
        volumes:
            - .:/app

    nginx:
         image: nginx:latest
         depends_on:
             - php
         ports:
             - "8080:80"
         volumes:
            - .:/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
